name: University of Bremen -- Python Tutorials
theme: jekyll-theme-Hacker

markdown: kramdown

kramdown:
  input: GFM
  math_engine: nil
  parse_block_html: true
  
  
defaults:
  - scope:
      path: "" 
    values:
      layout: "default" 

toc: true

